version: "3.9"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: my-laravel-app
        container_name: my-laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            - APP_ENV=local
        networks:
            - app-network
        depends_on:
            - mysql
    nginx:
        image: nginx:1.21
        container_name: my-nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - app-network
#    node:
#        build:
#            context: .
#            dockerfile: Dockerfile.node
#        image: my-laravel-node
#        container_name: my-laravel-node
#        ports:
#            - "3000:3000"
#        restart: unless-stopped
#        working_dir: /var/www
#        volumes:
#            - ./:/var/www
#            - /var/www/node_modules
#        networks:
#            - app-network
    mysql:
        image: mariadb:10.8.3
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - app-network
        ports:
            - "3307:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        depends_on:
            - mysql
        networks:
            - app-network
#    mailhog:
#        image: mailhog/mailhog
#        ports:
#            - 1025:1025
#            - 8025:8025
#        networks:
#            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    dbdata:
        driver: local
